apiVersion: v1
kind: ResourceQuota
metadata:
  name: httpbin-quota
  namespace: httpbin
spec:
  hard:
    pods: "16"
    requests.cpu: "1"
    requests.memory: 128Mi
    limits.cpu: "2"
    limits.memory: 256Gi