{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "httpbin.fullname" . }}-quota
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .Values.resourceQuota.spec | nindent 2 }}
{{- end }}